# Introduction Numpy

In [1]:
import numpy

# Creating a numpy array
arr = numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [2]:
# Numpy is usually imported under the np alias
import numpy as np

# Access Numpy Libary using np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [3]:
# diamention check
print(arr.ndim)

1


## Numpy shape

In [6]:
arr1 = np.array(
    [
        [1,2,3,4],
        [5,6,7,7]
    ]
)

In [8]:
print(arr1.ndim)
print(arr1.shape)

2
(2, 4)


## Numpy Reshape

In [13]:
import numpy as np

# creating a Numpy array
arr = np.array([1,2,3,4,5,6])
print(arr)

# reshaping the array to 2x3 matrix
reshpape_arr = arr.reshape(2,3)
print(reshpape_arr)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## Numpy Array indexing

In [14]:
arr = np.array([1.1,5,2,'True','Man'])
print(arr)

['1.1' '5' '2' 'True' 'Man']


In [15]:
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[0] + arr[2])

1
4


In [18]:
# access 2D arrays
arr = np.array([
    [1,2,3,4],
    [1,2,3,4]
])
print(arr[0][3])

4


In [23]:
# 3D array
arr = np.array([
    [
        [1,2,4],
        [1,2,3]
    ],
    [
        [1,2,4],
        [4,5,6]
    ]
])

print(arr[0,1,2])
print(arr[0][1][1])

3
2


In [22]:
# Negative Indexing
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

print(arr[0][-1])

5


# Numpy Array Iterating

In [26]:
# For loop

import numpy as np

arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

# Iterating through a 2D array using a nested Loop

for row in arr:
    for item in row:
        print(item,end=" ")
    print()


1 2 3 4 5 
6 7 8 9 10 


In [27]:
# 1D array
arr = np.array([1,2,3])

for i in arr:
    print(i)

1
2
3


In [28]:
# 3D iter
# 3D array
arr = np.array([
    [
        [1,2,4],
        [1,2,3]
    ],
    [
        [1,2,4],
        [4,5,6]
    ]
])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
4
1
2
3
1
2
4
4
5
6


# Numpy Array Slicing
* [:end] 0 to end
* [start:end]: start to end
* [start:] start to last index
* [::step] start to end increment to step
* [start:end:step] start to end follows given steps

In [32]:
# creating a numpy array
arr = np.array([1,2,4,5,6])

# Slicing from beginning to index 6
s1 = arr[:6]
print(s1)

# Slicing from index 2 to index 5
s2 = arr[2:5]
print(s2)

# Slicing from 3 to end
s3 = arr[3:]
print(s3)

# Slicing with a step of 2
s4 = arr[::2]
print(s4)

# Slicing with start:end:step
s5 = arr[2::]
print(s5)

[1 2 4 5 6]
[4 5 6]
[5 6]
[1 4 6]
[4 5 6]


In [35]:
# Creating a 2D Numpy Array and Apply Slicing

arr = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

# Slicing rows
row = arr[1]
print(row)
col = arr[:,1]
print(col)

[4 5 6]
[2 5 8]


In [36]:
# arr[row,col]
matrix = arr[:2,1:]
print(matrix)

[[2 3]
 [5 6]]


## Numpy DataTypes

In [40]:
arr = np.array([1,2,3])
print(arr.dtype)
arrb = np.array([1.4,13.4])
print(arrb.dtype)

int32
float64


In [45]:
# Specifying data types in Numpy arrays
arr_int32 = np.array([1,2,3],dtype=np.int32)
arr_float64 = np.array([1.4,2.4])
print(arr_int32)
print(arr_float64)

[1 2 3]
[1.4 2.4]


In [46]:
# Convertion between data types

arr = np.array([1,2,3])
# Convert to float 64
arr_float64 = arr.astype(np.float64)
print(arr_float64)

[1. 2. 3.]


## Joining Numpy Arrays

In [48]:
# Concatenation using np.concatenate

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

result = np.concatenate((arr1,arr2))
print(result)

[1 2 3 4 5 6]


## Splitting Numpy Arrays


In [49]:
# Creating data using np.arange
arr = np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [50]:
# Splitting the array into 3 quals parts
split_arr = np.split(arr,3)
print(split_arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [53]:
print(split_arr[1][2])

6


In [54]:
# Unqual splitting with np.array_split
unequal_split = np.array_split(arr,4)
print(unequal_split)

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]


## Numpy Searching Arrays

In [56]:
arr = np.arange(1,10)
# Finding indices where the value is greater that 3
index = np.where(arr > 3)
print(index)

(array([3, 4, 5, 6, 7, 8], dtype=int64),)


In [59]:
arr = np.array([10,2,5,7,8])
index = np.where(arr > 5)
print(index)

(array([0, 3, 4], dtype=int64),)


## Array Masking

In [60]:
# Creating a boolean mask means showing values
mask  = arr > 5
filtered_values = arr[mask]
print(filtered_values)

[10  7  8]


## Numpy Sorting Arrays

In [62]:
arr = np.array([1,4,5,1,7])
sorted_arr = np.sort(arr)
print(sorted_arr)

[1 1 4 5 7]


In [63]:
# Reverse
ultra_sort = np.sort(arr)[::-1]
print(ultra_sort)

[7 5 4 1 1]


In [69]:
# 2d Array Sort
arr_2d = np.array([
    [1,2,5],
    [0,4,8]
])

# Sort along rows (axis=1)
sorted_rows = np.sort(arr_2d,axis = 1)
print(sorted_rows)

# Sort along cols (axis=0)
sorted_cols = np.sort(arr_2d,axis=0)
print(sorted_cols)


[[1 2 5]
 [0 4 8]]
[[0 2 5]
 [1 4 8]]


## Array Operation

In [67]:
arr1 = np.array([1,2,4])
arr2 = np.array([1,2,4])
mul = arr1*arr2
print(mul)
print(arr1 + arr2)

[ 1  4 16]
[2 4 8]


## Descriptive Statistics
Mean, Median,Variance, and Standared Deviation

In [71]:
data = np.array([10,20,30,40,50])

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_dev = np.std(data)

print(mean)
print(median)
print(variance)
print(std_dev)

30.0
30.0
200.0
14.142135623730951


## Handiling Missing Values


In [76]:
# np.nan means no value or null
data = np.array([1,2,np.nan,4,5,np.nan,7])
print(data)

# Checking for NAN values
nan_count = np.sum(np.isnan(data))
print(nan_count)

[ 1.  2. nan  4.  5. nan  7.]
2


In [79]:
# Removing Nan values
data_cleaned = data[~np.isnan(data)]
print(data_cleaned)

[1. 2. 4. 5. 7.]


In [80]:
# Handiling missing values

#Calculate mean values excluding all nan
mean = np.nanmean(data)

# replacing nan values with mean value
data_filled = np.where(np.isnan(data),mean,data)
print(data_filled)


[1.  2.  3.8 4.  5.  3.8 7. ]
